<a href="https://colab.research.google.com/github/ShinwooChoi/ESAA-OB/blob/main/11_07_ESAA_OB_%ED%95%84%EC%82%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

범위: <딥러닝 파이토치 교과서> 1-2장 p.18-60

### 1.1 인공지능, 머신러닝, 딥러닝

#### 인공지능(AI)
- 인간의 지능을 모방하여 컴퓨터가 인간의 일을 수행할 수 있도록 하는 기술  
- 구현 방법: **머신러닝(Machine Learning)**, **딥러닝(Deep Learning)**  

#### 계층적 관계
> 인공지능 ＞ 머신러닝 ＞ 딥러닝  

- AI(전체 개념)  
- ML(AI를 구현하는 방법)  
- DL(ML의 세부 영역, 신경망 기반)  

#### 머신러닝 vs 딥러닝
| 구분 | 머신러닝 | 딥러닝 |
|------|-----------|---------|
| **동작 원리** | 입력 데이터에 알고리즘 적용해 예측 수행 | 신경망을 사용해 데이터의 특징·관계 해석 |
| **재사용** | 동일한 유형의 데이터 재사용 어려움 | 학습된 모델로 다양한 데이터 재사용 가능 |
| **데이터 규모** | 수천 개 수준 필요 | 수백만 개 이상 필요 |
| **훈련 시간** | 단시간 | 장시간 |
| **결과 형태** | 수치(점수·분류) | 이미지, 텍스트, 소리 등 다양한 형태 |

#### 머신러닝과 딥러닝의 차이
- **머신러닝** : 사람이 데이터를 전처리 후 컴퓨터가 학습  
- **딥러닝** : 컴퓨터가 스스로 데이터 특징을 추출·학습  

### 1.2 머신러닝이란

#### 정의
- 인공지능의 한 분야로, **컴퓨터가 데이터에서 학습하여 스스로 예측·판단하는 기술**

#### 머신러닝 학습 과정
- 주요 단계: **데이터 입력 → 특징 추출 → 모델 학습 → 예측 결과**
- **훈련(train)** : 주어진 데이터로 모델을 학습  
- **테스트(test)** : 새로운 데이터로 모델의 예측 성능 평가  

#### 머신러닝 구성요소
- **데이터(Data)** : 입력되는 학습 자료  
- **모델(Model)** : 학습 알고리즘  
- **평가(Evaluation)** : 정확도·오차율 측정  

#### 데이터 구분
| 구분 | 설명 |
|------|------|
| **훈련 데이터(Training)** | 모델 학습용 데이터 |
| **검증 데이터(Validation)** | 학습 중 성능 확인용 |
| **테스트 데이터(Test)** | 최종 평가용 데이터 |

#### 머신러닝 학습 순서
1. 모델 구조 설계  
2. 데이터 입력 및 학습  
3. 평가 후 모델 업데이트  

#### 머신러닝의 주요 알고리즘 분류
| 구분 | 학습 방식 | 예시 알고리즘 |
|------|------------|----------------|
| **지도 학습 (Supervised Learning)** | 입력(X)과 정답(Y) 존재 | K-NN, SVM, 선형/로지스틱 회귀 |
| **비지도 학습 (Unsupervised Learning)** | 정답 없이 패턴 탐색 | K-평균, DBSCAN 등 군집화 |
| **차원 축소 (Dimensionality Reduction)** | 데이터 축소 및 시각화 | PCA, ICA 등 |
| **강화 학습 (Reinforcement Learning)** | 보상 기반 행동 학습 | Q-Learning, MDP 등 |

#### 지도 학습 (Supervised Learning)
- 정답(label)이 있는 데이터를 학습하여 예측  
- 예: 입력 7×1=7, 7×2=14 → 7×3 예측  
- 회귀(Regression), 분류(Classification) 모두 포함  

#### 비지도 학습 (Unsupervised Learning)
- 정답이 없는 데이터에서 **패턴·유사도** 탐색  
- 예: 데이터 군집화(클러스터링)  

#### 강화 학습 (Reinforcement Learning)
- **보상(reward)** 을 통해 올바른 행동을 학습  
- 반복 시행 → 보상이 큰 행동 선택  
- 예: 게임에서 점수·성과를 통해 행동을 개선  

### 1.3 딥러닝이란

#### 정의
- 인간의 신경망 원리를 모방한 인공 신경망 이론 기반의 머신러닝 방법  
- 인간의 뇌 뉴런(neuron)과 시냅스(synapse)의 작동 원리를 모델링  

#### 뉴런 구성요소
- **수상돌기** : 다른 뉴런의 자극을 받아들이는 부분  
- **세포체** : 입력 신호를 통합하고 다음 뉴런으로 전달 준비  
- **축삭돌기** : 전기 신호를 전달하는 긴 돌기  
- **축삭종말** : 다음 뉴런의 수상돌기에 신호 전달  


### 1.3.1 딥러닝 학습 과정

#### 전체 과정
- 머신러닝과 유사하지만 더 복잡한 모델 구조를 사용  
- **단계**: 데이터 준비 → 모델 정의 → 모델 학습 → 손실 함수 계산 → 모델 평가  

#### 데이터 준비
- 학습용 데이터를 구축하는 단계  
- 효율적 데이터 준비를 위해 오픈소스 데이터셋(PyTorch, Keras 등)을 활용  

#### 모델 정의
- 모델의 입력, 은닉, 출력층을 정의  
- 층(layer) 개수·활성화 함수·가중치 등을 설정  

#### 모델 학습
- 학습 데이터를 이용해 손실 최소화  
- 손실 함수 예시: **MSE(평균제곱오차)**, **Cross Entropy(교차 엔트로피)**  

#### 배치 학습
- 데이터를 여러 묶음(batch)으로 나누어 학습  
- 예: 데이터 1000개, 배치 크기 20 → 50번 업데이트 진행  

#### 모델 평가
- 학습된 모델의 성능(performance)을 측정  
- 손실이 낮을수록 성능 우수  

#### 모델 연결(신경망 구조)
- **입력층(Input Layer)** : 데이터 입력  
- **은닉층(Hidden Layer)** : 계산 및 특징 추출  
- **출력층(Output Layer)** : 최종 결과 도출  

#### 역전파(Backpropagation)
- 오차를 기반으로 가중치를 업데이트하는 과정  
- 파이토치 등의 프레임워크를 통해 자동으로 처리 가능  



### 1.3.2 딥러닝 학습 알고리즘

#### 종류
- 머신러닝과 마찬가지로 **지도 학습**, **비지도 학습**, **강화 학습**으로 구분  

#### 주요 알고리즘
| 구분 | 알고리즘 | 특징 |
|------|-----------|------|
| **합성곱 신경망 (CNN)** | 이미지 처리에 특화 | 시각 인식, X-ray, CT 등 |
| **순환 신경망 (RNN)** | 시계열 데이터 분석 | 주식, 음성, 텍스트 |
| **LSTM** | RNN의 장기 의존성 문제 개선 | 긴 시퀀스 처리 |
| **워드 임베딩 (Word2Vec)** | 단어 의미를 벡터로 표현 | 자연어 처리 |
| **군집화 (Clustering)** | 유사 데이터 묶기 | 비지도 학습 |
| **전이 학습 (Transfer Learning)** | 기존 모델을 재활용 | 소량 데이터로 고성능 모델 구현 |



#### 전이 학습(Transfer Learning)
- 이미 학습된 모델(Pre-trained Model)을 새로운 데이터에 재사용  
- 기존 학습된 지식을 바탕으로 새로운 문제 해결  

#### 전이 학습 모델 예시
- **VGG**, **Inception**, **MobileNet** 등  
- 소량 데이터에서도 빠르고 효율적인 학습 가능  

#### 전체 학습 방식 요약
| 구분 | 유형 | 대표 알고리즘 |
|------|------|----------------|
| **지도 학습** | 이미지, 시계열 데이터 | CNN, RNN, ResNet |
| **비지도 학습** | 군집화 | K-평균, SOM |
| **전이 학습** | 사전 학습 모델 활용 | MobileNetV2 |
| **강화 학습** | 보상 기반 행동 학습 | Q-Learning, MDP |




## 2.1 파이토치 개요

#### 정의
- **PyTorch**는 2017년 공개된 딥러닝 프레임워크로, 파이썬 기반의 동적 계산 그래프를 사용하는 라이브러리  
- GPU 가속과 텐서 연산을 지원하여 빠르고 유연한 모델 구축 가능  

#### 사용 목적
- **딥러닝 연구 개발용** (속도, 효율성 중시)  
- **복잡한 수학 연산, GPU 병렬 연산이 필요한 경우**  


### 2.1.1 파이토치 특징 및 장점

#### 주요 구성요소
| 구성요소 | 설명 |
|-----------|------|
| **GPU** | 병렬 연산 처리, CUDA·cuDNN 통해 고속 계산 가능 |
| **텐서(Tensor)** | 파이토치의 기본 데이터 구조, NumPy 배열과 유사 |
| **동적 신경망(Define by Run)** | 실행 시점에 그래프 생성, 유연한 디버깅 가능 |

#### 장점 요약
- GPU 가속 지원으로 빠른 연산 가능  
- 직관적 문법으로 디버깅이 용이함  
- 계산 그래프를 런타임에 생성 → 직관적인 코드 구조  


### 2.1.2 파이토치의 아키텍처

#### 구조 개요
- **3계층 구조**:  
  1. 사용자 API (Python)  
  2. 중간 계층 (Autograd, Aten, JIT 등)  
  3. 하위 계층 (CUDA, cuDNN 등)

#### 주요 패키지 구성
| 패키지 | 설명 |
|---------|------|
| **torch** | 기본 텐서 연산 지원 |
| **torch.autograd** | 자동 미분 기능 제공 |
| **torch.nn** | 신경망 모듈 정의 및 학습 |
| **torch.multiprocessing** | 병렬 연산 지원 |
| **torch.utils** | DataLoader 등 유틸리티 포함 |

#### 파이토치 엔진
- **Autograd C++** : 자동 미분  
- **Aten C++** : 텐서 연산  
- **JIT C++** : 최적화된 런타임 실행  
- **CUDA/cuDNN** : GPU 가속 지원  


## 2.2 파이토치 기초 문법

### 2.2.1 텐서 다루기

#### 텐서 정의
- 파이토치의 기본 자료 구조  
- NumPy의 ndarray와 유사하지만 **GPU 연산 가능**

###2.2.2 데이터 준비
데이터 불러오기

Pandas 라이브러리를 활용해 CSV, JSON 등 파일을 읽음

데이터는 Tensor 형태로 변환해 모델 학습에 사용


###2.2.3 모델 정의

모델은 계층(layer)으로 구성

nn.Module 클래스를 상속받아 사용자 정의 가능


### 2.2.4 모델의 파라미터 정의
- 손실 함수 (Loss Function)

| 함수명                  | 용도    |
| -------------------- | ----- |
| **BCELoss**          | 이진 분류 |
| **CrossEntropyLoss** | 다중 분류 |
| **MSELoss**          | 회귀 문제 |

- 옵티마이저 (Optimizer)

| 메서드                  | 설명       |
| -------------------- | -------- |
| **optimizer.step()** | 가중치 업데이트 |
| **zero_grad()**      | 기울기 초기화  |

- 스케줄러 (Scheduler)

학습률을 점진적으로 조절하는 기능

예: torch.optim.lr_scheduler.StepLR

## 2.2.5 모델 훈련

#### 개념
- 모델의 가중치(파라미터)를 데이터로 학습시키는 과정  
- 예: `y = wx + b` 형태에서 `w`, `b`를 최적화  

#### 주요 메서드
| 메서드 | 설명 |
|--------|------|
| `optimizer.zero_grad()` | 이전 단계에서 계산된 기울기를 0으로 초기화 |
| `loss.backward()` | 손실 함수의 기울기 계산 |
| `optimizer.step()` | 계산된 기울기를 바탕으로 가중치 업데이트 |

#### 학습 순서 비교
| 구분 | 딥러닝 학습 절차 | 파이토치 학습 절차 |
|------|------------------|--------------------|
| 1 | 모델, 손실함수, 옵티마이저 정의 | 동일 |
| 2 | 학습 데이터 반복 처리 | `for`문 사용 |
| 3 | 예측 및 손실 계산 | `loss = fn(output, target)` |
| 4 | 역전파 수행 | `loss.backward()` |
| 5 | 가중치 업데이트 | `optimizer.step()` |



### 2.2.6 모델 평가

#### 개념
- 학습된 모델을 **테스트 데이터**로 평가  
- 평가 시 **정확도(accuracy)**, **혼동행렬(confusion matrix)** 등을 사용  


###2.2.7 훈련 과정 모니터링
개념

학습 중 손실(loss)·정확도(acc) 변화를 시각화하여 추적

TensorBoard를 이용해 학습 과정을 실시간으로 모니터링 가능

In [1]:
import torch
torch.tensor([[1.,-1.], [1.,-1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [2]:
import torch
print(torch.tensor([[1,2], [3,4]]))
print(torch.tensor([[1,2], [3,4]], device="cuda:0"))
print(torch.tensor([[1,2], [3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
temp=torch.tensor([[1,2], [3,4]])
print(temp.numpy())

temp=torch.tensor([[1,2], [3,4]], device="cuda:0")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
temp=torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0], temp[1], temp[-1])
print('------------------------')
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [5]:
v=torch.tensor([1,2,3])
w=torch.tensor([3,4,6])
print(w-v)

tensor([2, 2, 3])


In [6]:
temp=torch.tensor([
    [1,2], [3,4]])

print(temp.shape)
print('---------------------')
print(temp.view(4,1))
print('---------------------')
print(temp.view(-1))
print('---------------------')
print(temp.view(1,-1))
print('---------------------')
print(temp.view(-1,1))

torch.Size([2, 2])
---------------------
tensor([[1],
        [2],
        [3],
        [4]])
---------------------
tensor([1, 2, 3, 4])
---------------------
tensor([[1, 2, 3, 4]])
---------------------
tensor([[1],
        [2],
        [3],
        [4]])


In [9]:
!pip install pandas

In [11]:
'''
import pandas as pd
import torch
data=pd.read_csv('../class2.csv')

x=torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
y=torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()
'''

"\nimport pandas as pd\nimport torch\ndata=pd.read_csv('../class2.csv')\n\nx=torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()\ny=torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()\n"

In [12]:
'''
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
    def __len__(self):
    def __getitem__(self, index):
'''

'\nclass CustomDataset(torch.utils.data.Dataset):\n    def __init__(self):\n    def __len__(self):\n    def __getitem__(self, index):\n'

In [13]:
'''
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
    def __init__(self, csv_file):
        self.label=pd.read_csv(csv_file)

    def __len__(self):
        return len(self.label)

    def __getitem__(self, idx):
        sample=torch.tensor(self.label.iloc[idx, 0:3]).int()
        label=torch.tensor(self.label.iloc[idx, 3]).int()
        return sample, label

tensor_dataset=CustomDataset('../covtype.csv')
dataset=DataLoader(tensor_dataset, batch_size=4, shuffle=True)
'''

"\nimport pandas as pd\nimport torch\nfrom torch.utils.data import Dataset\nfrom torch.utils.data import DataLoader\n\nclass CustomDataset(Dataset):\n    def __init__(self, csv_file):\n        self.label=pd.read_csv(csv_file)\n\n    def __len__(self):\n        return len(self.label)\n\n    def __getitem__(self, idx):\n        sample=torch.tensor(self.label.iloc[idx, 0:3]).int()\n        label=torch.tensor(self.label.iloc[idx, 3]).int()\n        return sample, label\n\ntensor_dataset=CustomDataset('../covtype.csv')\ndataset=DataLoader(tensor_dataset, batch_size=4, shuffle=True)\n"

In [14]:
'''
for i, data in enumerate(dataset, 0):
    print(i, end='')
    batch=data[0]
    print(batch.size())
'''

"\nfor i, data in enumerate(dataset, 0):\n    print(i, end='')\n    batch=data[0]\n    print(batch.size())\n"

In [15]:
!pip install requests

In [16]:
import torchvision.transforms as transforms

mnist_transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
])


from torchvision.datasets import MNIST
import requests

download_root='../chap02/data/MNIST_DATASET'

train_dataset=MNIST(download_root, transform=mnist_transform, train=True,
                    download=True)
valid_dataset=MNIST(download_root, transform=mnist_transform, train=False,
                    download=True)
test_dataset=MNIST(download_root, transform=mnist_transform, train=False,
                   download=True)

100%|██████████| 9.91M/9.91M [00:00<00:00, 20.7MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 561kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.81MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 10.8MB/s]


In [17]:
import torch.nn as nn
model=nn.Linear(in_features=1, out_features=1, bias=True)

In [18]:

class MLP(nn.Module):
    def __init__(self, inputs):
        super(MLP, self).__init__()
        self.layer=Linear(inputs, 1)
        self.activation=Sigmoid()

    def forward(self, X):
        X=self.layer(X)
        X=self.activation(X)
        return X

In [19]:
import torch.nn as nn
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layer1=nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2))

        self.layer2=nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2))

        self.layer3=nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True))

    def forward(self,x):
        x=self.layer1(x)
        x=self.layer2(x)
        x=x.view(x.shape[0],-1)
        x=self.layer3(x)
        return x
model=MLP()

print("Printing children\n-----------------------")
print(list(model.children()))
print("\n\nPrinting Modules\n-------------------------")
print(list(model.modules()))

Printing children
-----------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_feature

In [20]:
def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden=nn.Linear(in_features=in_features, out_features=hidden_features,
                     bias=True)
    activation=nn.ReLU()
    output=nn.Linear(in_features=hidden_features, out_features=out_features,
                     bias=True)
    net=nn.Sequential(hidden, activation, output)
    return net

In [22]:
'''
from torch.optim import optimizer
criterion=torch.nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
scheduler=torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer,
                                            lr_lambda=lambda epoch: 0.95**epoch)

for epoch in range(1, 100+1):
   for x, y in dataloader:
        optimizer.zero_grad()
loss_fn(model(x), y).backward()
optimizer.step()
scheduler.step()

'''

'\nfrom torch.optim import optimizer\ncriterion=torch.nn.MSELoss()\noptimizer=torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)\nscheduler=torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer,\n                                            lr_lambda=lambda epoch: 0.95**epoch)\n\nfor epoch in range(1, 100+1):\n   for x, y in dataloader:\n        optimizer.zero_grad()\nloss_fn(model(x), y).backward()\noptimizer.step()\nscheduler.step()\n\n'

In [23]:
'''
for epoch in range(100):
   yhat=model(x_train)
    loss=criterion(yhat, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
'''

'\nfor epoch in range(100):\n   yhat=model(x_train)\n    loss=criterion(yhat, y_train)\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()\n'

In [24]:
!pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 23.1 MB/s eta 0:00:00


In [32]:
'''
import torch
import torchmetrics

preds=torch.randn(10,5).softmax(dim=-1)
target=torch.randint(5, (10,))

acc=torchmetrics.functional.accuracy(preds, target)
'''

'\nimport torch\nimport torchmetrics\n\npreds=torch.randn(10,5).softmax(dim=-1)\ntarget=torch.randint(5, (10,))\n\nacc=torchmetrics.functional.accuracy(preds, target)\n'

In [26]:
'''
import torch
import torchmetrics
metric=torchmetrics.Accuracy()

n_batches=10
for i in range(n_batches):
  preds=torch.randn(10,5).softmax(dim=-1)
  target=torch.randint(5, (10,))

  acc=metric(preds, target)
  print(f"Accuracy on batch {i}: {acc}")

acc=metric.compute()
print(f"Accuracy on all data: {acc}")
'''

'\nimport torch\nimport torchmetrics\nmetric=torchmetrics.Accuracy()\n\nn_batches=10\nfor i in range(n_batches):\n  preds=torch.randn(10,5).softmax(dim=-1)\n  target=torch.randint(5, (10,))\n\n  acc=metric(preds, target)\n  print(f"Accuracy on batch {i}: {acc}")\n\nacc=metric.compute()\nprint(f"Accuracy on all data: {acc}")\n'

In [27]:
!pip install tensorboard

In [28]:
'''
import torch
from torch.utils.tensorboard import SummaryWriter

writer=SummaryWriter('../chap02/tensorboard')

for epoch in range(num_epochs):
    model.train()
    batch_loss=0.0

for i, (x,y) in enumerate(dataloader):
    x, y=x.to(device).float(), y.to(device).float()
    outputs=model(x)
    loss=criterion(outputs, y)
    writer.add_scalar('Loss', loss, epoch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

writer.close()
'''

"\nimport torch\nfrom torch.utils.tensorboard import SummaryWriter\n\nwriter=SummaryWriter('../chap02/tensorboard')\n\nfor epoch in range(num_epochs):\n    model.train()\n    batch_loss=0.0\n\nfor i, (x,y) in enumerate(dataloader):\n    x, y=x.to(device).float(), y.to(device).float()\n    outputs=model(x)\n    loss=criterion(outputs, y)\n    writer.add_scalar('Loss', loss, epoch)\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()\n\nwriter.close()\n"

In [34]:
'''
tensorboard --logdir=../chap02/tensorboard --port=6006
'''

'\ntensorboard --logdir=../chap02/tensorboard --port=6006\n'

In [33]:
'''
model.eval()
with torch.no_grad():
    valid_loss=0

    for x, y in valid_dataloader:
        outputs=model(x)
        loss=F.cross_entropy(outputs, y.long().squeeze)
        valid_loss+=float(loss)
        y_hat+=[outputs]

valid_loss=valid_loss/len(valid_loader)
'''

'\nmodel.eval()\nwith torch.no_grad():\n    valid_loss=0\n\n    for x, y in valid_dataloader:\n        outputs=model(x)\n        loss=F.cross_entropy(outputs, y.long().squeeze)\n        valid_loss+=float(loss)\n        y_hat+=[outputs]\n\nvalid_loss=valid_loss/len(valid_loader)\n'